[package]
name = "min_mag"
version = "0.1.0"
edition = "2021"

[dependencies]
hound = "3.5"
rustfft = "6.1"
indicatif = "0.17"

[profile.release]
panic = "abort"
debug = false
strip = true
lto = true

[profile.release.package."*"]
debug = false

[workspace]
resolver = "2"
